// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = (import.meta.env.VITE_SUPABASE_URL ?? "https://knvnbkjggwqojqvdjfxa.supabase.co") as string;
const SUPABASE_PUBLISHABLE_KEY = (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtudm5ia2pnZ3dxb2pxdmRqZnhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE5NTQ3MzUsImV4cCI6MjA4NzUzMDczNX0.0ESTp1v59QKnOQOJdiPJwW0b018-Q5Z1JCks0tFywbU") as string;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});